# This is a config for E2B sandbox template.
# You can use template ID (tadblf6vtrb9ooo85ila) or template name (vibe-nextjs-test-0000) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibe-nextjs-test-0000") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-test-0000") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-test-0000')

team_id = "5443442f-c10a-402d-b2c1-f70192123863"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-test-0000"
template_id = "tadblf6vtrb9ooo85ila"
